var result = 0;
var operation;
var input = document.getElementById('input');
var btnMinus = document.getElementById('minus');
var btnPlus = document.getElementById('sum');
var btnMultiply = document.getElementById('multiply');
var btnEqually = document.getElementById('equally');
var btnDivision = document.getElementById('division');
var btnClear = document.getElementById('clear');
var btnReset = document.getElementById('reset');
var btnPoint = document.getElementById('point');

numberButtonInitialization(input);
btnMinus.addEventListener("click", minus);
btnMultiply.addEventListener("click", multiplication);
btnDivision.addEventListener("click", division);
btnPlus.addEventListener("click", plus);
btnReset.addEventListener("click", reset);
btnClear.addEventListener("click", clear);
btnPoint.addEventListener("click", coma);
btnEqually.addEventListener("click",  equally);